project_id = "wkoroqknbgxsmtuqmvzm"

[functions.auth-login]
verify_jwt = false

[functions.auth-register]
verify_jwt = false

[functions.auth-set-password]
verify_jwt = false

[functions.auth-verify]
verify_jwt = false

[functions.auth-invite-user]
verify_jwt = true

[functions.empresas-sync]
verify_jwt = false

[functions.empresas-create]
verify_jwt = true

[functions.empresas-update]
verify_jwt = true

[functions.empresas-delete]
verify_jwt = true

[functions.empresas-list]
verify_jwt = true

[functions.cep-lookup]
verify_jwt = false
